# Generated by Django 5.1.4 on 2024-12-24 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_chat_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaveItem',
            new_name='UserSaveItem',
        ),
        migrations.CreateModel(
            name='UserSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_save', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='usersaveitem',
            name='save',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='instagram.usersave'),
        ),
        migrations.DeleteModel(
            name='Save',
        ),
    ]
