# Generated by Django 5.1.4 on 2024-12-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_rename_saveitem_usersaveitem_usersave_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersaveitem',
            old_name='post',
            new_name='post_item',
        ),
        migrations.RenameField(
            model_name='usersaveitem',
            old_name='save',
            new_name='save_item',
        ),
    ]
